global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'openwms'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
#    dns_sd_configs:
#      - names:
#          - 'tasks.cadvisor'
#        type: 'A'
#        port: 8080
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'COMMON: Services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['common-service:8120']

  - job_name: 'COMMON: TCP/IP Palett'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tcpip-palettconv:30008']

  - job_name: 'WMS: Inventory'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wms-inventory:8140']

  - job_name: 'WMS: Receiving'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wms-receiving:8141']

  - job_name: 'WMS: Shipping'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wms-shipping:8132']

  - job_name: 'TMS: Routing'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['routing-service:8130']

  - job_name: 'TMS: Transportation'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tms-service:8131']

  - job_name: 'CORE: Printing'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['printing-service:8133']

  - job_name: 'CORE: Gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8086']

  - job_name: 'CORE: Service Registry'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'user'
      password: 'sa'
    static_configs:
      - targets: ['srv:8990']

  - job_name: 'CORE: Configuration Service'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'user'
      password: 'sa'
    static_configs:
      - targets: ['cfg:8099']
